const express = require('express');
const app = express();
const bodyParser = require('body-parser');
const MessagingResponse = require('twilio').twiml.MessagingResponse;
const axios = require('axios');
const moment = require('moment');
const mongoose = require('mongoose');
const Macro = require('./model.js');
const today = moment().format("MMM Do YY");

const PORT = process.env.PORT || 3000; // NEED TO CHANG THIS TO 9090 when hosting on HEROKU

// CONNECT TO A MONGO DATABASE (EITHER LOCAL OR HOSTED). 'TEST' IS AUTOGENERATED ALWAYS BY MONGODB 
// IN THIS INSTANCE I'M GONNA CONNECT TO MY MLAB 'BULKBOT' DATABASE, WOO!
mongoose.connect('mongodb://Tony:password@ds143734.mlab.com:43734/bulkybot');

// HELPER FUNCS
const hasNumber = str => /\d/.test(str);

// Parses incoming request bodies
app.use(bodyParser());


app.get("/", function (req, res) {
  res.send("Running smooth!");
});

app.post('/sms', (req, res) => {
  const twiml = new MessagingResponse();
  const textBody = req.body.Body;
  let date;
  let protein;
  let calories;

  switch (textBody) {
    case 'Hey': twiml.message('Hey hey hey!');
      break;
    default: { // THIS IS THE MEAT AND BONES OF BULKYBOT
      if (hasNumber(textBody)) {
        // SAVE PROTEIN/CALORIES TO THE MLAB DB
        new Macro({
          date: today,
          protein: 50,
          calories: 200
        })
        .save((err) => {
            if (err) console.log("ERROR");
        })

        // THIS WHOLE THING FRIKKIN WORKS! JUST NEED TO EXTRACT FROM THE 'TEXTBODY' NOW

      twiml.message(textBody);
        
      } else { // IF THERE'S NO NUMBERS IN THE TEXT BODY
        twiml.message('BulkyBot hears you!')
        writeHead();
      }

      return;
    };
  }

  res.writeHead(200, {'Content-Type': 'text/xml'});
  res.end(twiml.toString());
});



app.listen(PORT, (err) => {
  if (err) {
    console.log(err);
    process.exit();
  }
  console.log(`listening on port ${PORT}`);
});
